[project]
name = "test"
description = "Test for requirements"
version = "0.1.0"
authors = [
    { name = "Sam Mangham", email = "mangham@gmail.com" }
]
dependencies = [
    "numpy=^1.20.0",
]

[project.optional-dependencies]
dev = [
    "pandas",
]
